sonar.projectKey=QuelloCheVuoiTu_GestorePercorsi
sonar.organization=quellochevuoitusonar
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.test.js,**/*.spec.js,**/node_modules/**,**/dist/**,**/build/**,**/bin/**,**/.git/**,**/venv/**,**/*.png,**/*.jpg
sonar.java.binaries=**/build/classes,**/target/classes,**/bin
sonar.python.version=3.11
