sonar.projectKey=QuelloCheVuoiTu_GestorePercorsi
sonar.organization=quellochevuoitusonar
sonar.sources=.
sonar.sourceEncoding=UTF-8
# Esclusioni generiche per non sprecare righe di codice su file inutili
sonar.exclusions=**/*.test.js,**/*.spec.js,**/node_modules/**,**/dist/**,**/build/**,**/bin/**,**/obj/**,**/vendor/**,**/.git/**,**/venv/**,**/*.png,**/*.jpg,**/*.css
# Percorsi di fallback per binari Java/Kotlin/C#
sonar.java.binaries=**/build/classes,**/target/classes,**/bin/Debug/**,**/bin/Release/**
sonar.python.version=3.11
