name: 🐶 Snyk Security
on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '.github/workflows/**'
      - 'sonar-project.properties'
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - '.github/workflows/**'
      - 'sonar-project.properties'
  workflow_dispatch:

jobs:
  snyk-scan:
    name: Snyk Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install Snyk CLI
        run: npm install -g snyk snyk-to-html

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Test
        # Se 'true', la pipeline diventa verde anche se trova virus.
        # Se 'false', la pipeline diventa ROSSA e blocca le PR.
        continue-on-error: false
        run: |
          echo "Running Snyk (Threshold: medium)"
          snyk test --all-projects --severity-threshold=medium --json > snyk_report.json

      - name: Generate Report
        if: always()
        run: snyk-to-html -i snyk_report.json -o snyk_report.html

      - name: Snyk Monitor
        if: always()
        run: snyk monitor --all-projects || true

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with: { name: snyk-security-report, path: snyk_report.html }
